name: ecoscan
description: "A guest-first AI waste sorting web application by ToastTech."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.10.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^3.3.2
  firebase_ai: ^4.0.0
  firebase_app_check: ^0.4.8
  firebase_auth: ^6.2.0
  firebase_core: ^4.3.0
  cupertino_icons: ^1.0.8
  camera: ^0.11.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
