// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACb5jJ9rnnU9bcft0HBvqKLaABtbk2gEs',
    appId: '1:923392986981:web:e1f47c4bb9325c53861b8c',
    messagingSenderId: '923392986981',
    projectId: 'ecoscan-aaa86',
    authDomain: 'ecoscan-aaa86.firebaseapp.com',
    databaseURL: 'https://ecoscan-aaa86-default-rtdb.firebaseio.com',
    storageBucket: 'ecoscan-aaa86.firebasestorage.app',
    measurementId: 'G-0PVBH9G3CL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIdF1DwS_Cm9Fh-S5eVQ725af1zxfKkuU',
    appId: '1:923392986981:android:999b69c0eea72a3f861b8c',
    messagingSenderId: '923392986981',
    projectId: 'ecoscan-aaa86',
    databaseURL: 'https://ecoscan-aaa86-default-rtdb.firebaseio.com',
    storageBucket: 'ecoscan-aaa86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATmECA6Co1O9KAqq1C4mLj89mYPB6hMNM',
    appId: '1:923392986981:ios:8918dc9819494fa0861b8c',
    messagingSenderId: '923392986981',
    projectId: 'ecoscan-aaa86',
    databaseURL: 'https://ecoscan-aaa86-default-rtdb.firebaseio.com',
    storageBucket: 'ecoscan-aaa86.firebasestorage.app',
    iosClientId: '923392986981-9ruih5jkrqm7led1ujf9uas85n7du02r.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecoscan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATmECA6Co1O9KAqq1C4mLj89mYPB6hMNM',
    appId: '1:923392986981:ios:8918dc9819494fa0861b8c',
    messagingSenderId: '923392986981',
    projectId: 'ecoscan-aaa86',
    databaseURL: 'https://ecoscan-aaa86-default-rtdb.firebaseio.com',
    storageBucket: 'ecoscan-aaa86.firebasestorage.app',
    iosClientId: '923392986981-9ruih5jkrqm7led1ujf9uas85n7du02r.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecoscan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACb5jJ9rnnU9bcft0HBvqKLaABtbk2gEs',
    appId: '1:923392986981:web:50711477e5452c56861b8c',
    messagingSenderId: '923392986981',
    projectId: 'ecoscan-aaa86',
    authDomain: 'ecoscan-aaa86.firebaseapp.com',
    databaseURL: 'https://ecoscan-aaa86-default-rtdb.firebaseio.com',
    storageBucket: 'ecoscan-aaa86.firebasestorage.app',
    measurementId: 'G-V053PSFQ83',
  );

}